#!/bin/sh
### BEGIN INIT INFO
# Provides:          node-service
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export SERVER_PORT=80
export SERVER_IFACE='0.0.0.0'

if [ ! -d /app/log ]
then
   mkdir -p /app/log
   chmod 777 /app/log
fi

case "$1" in
  start)
  exec forever --sourceDir=/app --minUptime 1000 --spinSleepTime 1000 -p /app/log start server.js
  ;;

  stop)
  exec forever --sourceDir=/app stop server.js
  ;;
esac

exit 0
