---

- hosts: mongoserver
  become: yes
  roles:
  - mongo

- hosts: redisserver
  become: yes
  vars:
    - redis_bind: 0.0.0.0
  roles:
  - redis

- hosts: nodeserver
  become: yes
  roles:
  - nodejs
  - app
