---
# File: configure-systemd.yml
# Type: task
# Part: MongoDB

# - name: MongoDB | Backup service configuration
#   command: cp /lib/systemd/system/{{ mongodb_service }}.service /var/backups/{{ mongodb_service }}.service.bak
#   args:
#     creates: /var/backups/{{ mongodb_service }}.service.bak
#   register: result
# - fetch: src=/var/backups/{{ mongodb_service }}.service.bak dest=fetched
#   when: result|changed
- name: MongoDB | Deploy systemd service configuration
  template: src=mongod.service.j2 dest=/etc/systemd/system/{{ mongodb_service }}.service owner=root group=root mode=0644 backup=no
  notify: restart mongod
  register: result
- fetch: src=/etc/systemd/system/{{ mongodb_service }}.service   dest=fetched
  when: result|changed
