---
# File: main.yml
# Type: handler
# Part: NodeJS


- name: start nodejs
  service: name=nodejs state=started

- name: restart nodejs
  service: name=nodejs state=restarted

- name: reload supervisor
  shell: supervisorctl reload
  notify: ensure supervisor service

- name: ensure supervisor service
  action: service name=supervisor state=started
